name: Deploy to Hugging Face Spaces (Git Method)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-hf-space:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE_ID }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Add HF Space as remote
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE
          
          # Push to HF Space
          git push hf main --force
